<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ErpDotNet.Logic\ErpDotNet.Logic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Texts\MainViewTexts.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MainViewTexts.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Texts\MainViewTexts.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MainViewTexts.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
