//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpDotNet.Wpf.Texts {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainView() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErpDotNet.Wpf.Texts.MainView", typeof(MainView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERP.NET ähnelt.
        /// </summary>
        public static string View_Title {
            get {
                return ResourceManager.GetString("View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SQLite Database (*.db)|*.db ähnelt.
        /// </summary>
        public static string ViewModel_FileDialog_Filter {
            get {
                return ResourceManager.GetString("ViewModel_FileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose database file to open ähnelt.
        /// </summary>
        public static string ViewModel_OpenFileDialog_Title {
            get {
                return ResourceManager.GetString("ViewModel_OpenFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose folder and name for new database ähnelt.
        /// </summary>
        public static string ViewModel_SaveFileDialog_Title {
            get {
                return ResourceManager.GetString("ViewModel_SaveFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database created at  ähnelt.
        /// </summary>
        public static string ViewModel_StatusMessage_FileCreated {
            get {
                return ResourceManager.GetString("ViewModel_StatusMessage_FileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database NOT created ähnelt.
        /// </summary>
        public static string ViewModel_StatusMessage_FileNotCreated {
            get {
                return ResourceManager.GetString("ViewModel_StatusMessage_FileNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database file does not exist at  ähnelt.
        /// </summary>
        public static string ViewModel_StatusMessage_FileNotOpened {
            get {
                return ResourceManager.GetString("ViewModel_StatusMessage_FileNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database opened at  ähnelt.
        /// </summary>
        public static string ViewModel_StatusMessage_FileOpened {
            get {
                return ResourceManager.GetString("ViewModel_StatusMessage_FileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No card available for list type &quot;{0: list type}&quot; ähnelt.
        /// </summary>
        public static string ViewModel_StatusMessage_NoCardForListType {
            get {
                return ResourceManager.GetString("ViewModel_StatusMessage_NoCardForListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No open database to use ähnelt.
        /// </summary>
        public static string ViewModel_StatusMessage_NoDatabase {
            get {
                return ResourceManager.GetString("ViewModel_StatusMessage_NoDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No item selected to show in card ähnelt.
        /// </summary>
        public static string ViewModel_StatusMessage_NoItemSelectedForCard {
            get {
                return ResourceManager.GetString("ViewModel_StatusMessage_NoItemSelectedForCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to ERP.NET! ähnelt.
        /// </summary>
        public static string ViewModel_StatusMessage_Welcome {
            get {
                return ResourceManager.GetString("ViewModel_StatusMessage_Welcome", resourceCulture);
            }
        }
    }
}
